### PR TITLE
simplelog rotate

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by ktf** [comment]
Job hang, not sure where. Restarting now.

**Comment by sy-c** [comment]
Hello @ktf,
thanks for the action, but it is still stuck.

**Comment by ktf** [comment]
i will check in 15 min

**Comment by ktf** [comment]
Ok. Problem understood and fixed. My latest change in the way I report build results had a bug.

**Comment by sy-c** [comment]
@ktf thanks! should I re-trigger the check with a commit?

**Comment by ktf** [comment]
The linux one finally reported the result. The mac one is still building, apparently.

**Comment by ktf** [comment]
@awegrzyn do you use your own test machine for this?

**Comment by sy-c** [comment]
Hello @ktf @awegrzyn,
macos check is still stuck. How can we proceed with this PR? This is blocking other dev.

**Comment by awegrzyn** [comment]
@ktf nope, this is worker that was set up by Dario, I asked @MichaelLettrich to bring it back, as apparently it had not been working for days.

**Comment by awegrzyn** [comment]
@sy-c Now you can merge anytime

**Comment by sy-c** [comment]
thanks !

**Pull request merged**
