### PR TITLE
Remove classes that require additional deps than boost (OCCF-49)

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by dberzano** [comment]
I have updated it in order to see if the macOS test works!

**Comment by dberzano** [comment]
Note that the error is expected, I have interrupted it deliberately to see what was the outcome!

**Comment by dberzano** [comment]
Note that the error you see now is an actual error from Common. Good news is the PR test is up and running for mac.

**Comment by awegrzyn** [comment]
@dberzano on my mac both of them are warnings only. Does it suppose to be like this?

**Comment by dberzano** [comment]
We build with `defaults-o2`. Is it the case on your Mac? We are also running the latest version of everything (Xcode, macOS, and O2 from dev).

**Comment by awegrzyn** [comment]
yes, I have the newest Xcode as well but I'm building manually (without aliBuild)
```
/Users/awegrzyn/alice/Common/src/Daemon.cxx:97:10: warning: 'daemon' is deprecated: first deprecated in macOS 10.5 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
      if(daemon(1,~params.redirectOutput) == -1){
         ^
/usr/include/stdlib.h:293:6: note: 'daemon' has been explicitly marked deprecated here
int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
```

**Comment by dberzano** [comment]
Hi @awegrzyn, due to an unrelated change, we didn't re-test automatically the PR after alidist was updated. As you can see, it's now green (I have fixed the problem with the continuous integration.)

The reason why we used `-Werror` can be seen in `o2.sh`.

However, we should aim to warning-free code, and the warnings I see above can be easily fixed. One of them, in particular, is a quite grave warning and must not be overlooked:

```
/build/ci_checks/common_checker_macos_o2_ci_0/sw/SOURCES/O2/5/0/src/Daemon.cxx:97:10: error: 'daemon' is deprecated: first deprecated in macOS 10.5 - Use posix_spawn APIs instead. [-Werror,-Wdeprecated-declarations]
```

macOS 10.5 is 11 years old, it surprises me it hasn't yet gone from deprecated to eliminated, but it might really happen any time soon...

**Comment by awegrzyn** [comment]
Hi @dberzano, thanks for the follow up. I discussed it today with developers of `Common` and they will fix these warnings/errors. Although, they requested a way to run the tests on their local machine to  ensure it successfully completes. Do you know how we could achieve this? I guess setting test flag and compiling `O2` with `aliBuild` would do the job?

**Comment by dberzano** [comment]
The way we test is simply to run aliBuild. In our Common tests, we have Common as "development package" (source visible and under your control), and we build O2.

```
aliBuild build O2 --defaults o2
```

If you _also_ want to run `ctest`, you need to run:

```
ALIBUILD_O2_TESTS=1 aliBuild build O2 --defaults o2
```

**Comment by awegrzyn** [comment]
This is exactly what I thought about, thanks!

**Pull request closed without merging**
