### PR TITLE
added Timer::getRemainingTime()

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
@awegrzyn the macos build fails in monitoring. This looks to me unrelated to this PR.

**Review by Barthelemy — APPROVED** [review]
ok for the code. I let Adam discuss the compilation error.

**Comment by awegrzyn** [comment]
Indeed, looks like build machine is running old macOS (without variant). You can go ahead and merge.

**Comment by sy-c** [comment]
@awegrzyn : can you please merge? I don't have the rights...

**Pull request merged**
