### PR TITLE
Add badge for macOS CI

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@Barthelemy this is how the badge would look like. For the moment, I have added it only for the macOS CI of Common (it's not a very active project), but the idea is to extend it to every O2 project and every 

Clicking on the link brings you to the logfile. Note that you might get a 404 now, I will fix it (it's independent on this PR).

**Comment by dberzano** [comment]
p.s. I have deliberately made the build fail once to get a red badge, and succeeded 🎉

**Comment by dberzano** [comment]
For future reference, I have found out that GitHub caches images (through the camo service), including badges. This means that - by default - there's hours of inertia before the right badge color shows up, and it might take time before getting notified of a failed build.

Turns out the [camo service merely honors standard HTTP headers](https://github.com/github/markup/issues/224#issuecomment-35293273), so, since we're in control of ours (nginx), I had to modify a certain line to tell it to set the proper expiry headers for all .svg files:

```nginx
location ~ ^/repo {
  root   /usr/share/nginx/html;
  autoindex on;
  location ~ ^/repo/.*\.svg$ {
    expires -1;
  }
}
```

The nginx `expires -1` option adds:

```text
Cache-Control: no-cache
Expires: <current date>
```

to the .svg headers, making the badge indication work as expected.

**Comment by dberzano** [comment]
On the problem of caching, @awegrzyn might be interested.

**Comment by Barthelemy** [comment]
Thank you, very nice !

**Pull request merged**
