### PR TITLE
Set exit codes on Program failure

### PR DESCRIPTION
**Pull request by kostorr**
Related to O2-1577.

### CODE REVIEW

**Comment by kostorr** [comment]
Digging in alidist it seems that Readout, QualityControl and O2 are using this.
@sy-c, @Barthelemy, @ktf can you verify that this won't break anything on your side?

Exit codes are arbitrary, 2 for cli option errors, 1 for everything else.

**Comment by sy-c** [comment]
@kostorr no problem for me, I don't use this feature, thanks.

**Comment by Barthelemy** [comment]
We don't use it any more in the QC as we use DPL.

**Review by ktf — APPROVED** [review]
Fine with me.

**Pull request merged**
