### PR TITLE
file regenerated with swig 3.0.12…

### PR DESCRIPTION
**Pull request by sy-c**
… to get it in line with newer c++ standards

### CODE REVIEW

**Comment by ktf** [comment]
Given we do have swig available, why not fixing the `CMakeList.txt` to generate the file on the fly?

**Comment by sy-c** [comment]
> Given we do have swig available, why not fixing the CMakeList.txt to generate the file on the fly?

I didn't knew swig is available within O2.
I have done changes to CMakeList.txt and it generates the lib directly from the interface file using the cmake UseSWIG module and SWIG_ADD_LIBRARY macro.
However, on my dev setup, it does not seem to take swig from the aliBuild environment but from the system. I suspect one has to declare this build-time dependency somewhere in the bucket maybe? Do you have guidelines about that, or could you please point me to an existing O2 module using swig already?

Apart from these technical details, do we really want to re-generate this code at build time?
It makes the changes difficult to track, and adds an extra dependency. In my past experience with swig such code is stable and does not need updated unless interface is changed.

**Comment by ktf** [comment]
https://github.com/alisw/alidist/commit/7f386564a9d3772c760fafd191995234248ca001

should add the build time dependency to Common-O2.

My personal experience is that whatever is generated sooner or later breaks
and when you need to update it no one remembers how it was done (regardless
of the instructions, which get out of date in the meanwhile). Adding it as
a dependency makes sure that does not happen.

**Comment by sy-c** [comment]
I gave it a try, and swig indeed appears in the build-time dependency list for Common.
However, it does not seem to check what version is installed.
It works when swig is not detected and uses the alibuild-provided swig 3.0.7.
But if swig is installed on the system, it takes it whatever the version.
On CC7, the default version is 2.0.10, which generates source code not compliant with latest c++ standards and caused this pull request.
The updated code in this PR was generated from latest swig 3.0.12.

Is there a mean to enforce swig version to be at least the one coming with alibuild?
What about updating swig to 3.0.12 in alibuild?
3.0.7 is from Aug 2015.

**Comment by ktf** [comment]
So basically you are asking two things:

- [x] Move SWIG to 3.0.12
- [x] Add a version check for SWIG >= 3.0.12

Correct? Let me see if I can quickly do both.

**Comment by ktf** [comment]
See also alisw/alidist#999

**Comment by sy-c** [comment]
Hello again,
good, alibuild now builds 3.0.12 whenever necessary.

However, from the Common-O2 cmake, it's still the system swig which is used.
I suppose that it has to be dealt with in the Common-O2 recipe.
I have naively added the following line to cmake args in common-o2.sh following how it's done for boost, and it seems to do the trick and have find_package(SWIG) going to the good place:
      ${SWIG_VERSION:+-DSWIG_ROOT=$SWIG_ROOT}                 \
Is it the recommended way to proceed? Should I create the associated PR?

**Comment by sy-c** [comment]
For the records, location of SWIG binary can be checked in CMakeLists.txt with
    message(STATUS "SWIG_EXECUTABLE  = ${SWIG_EXECUTABLE}" )

**Comment by ktf** [comment]
That looks fine to me. Alternatively you could try:

```bash
${SWIG_VERSION:+-DSWIG_EXECUTABLE=$SWIG_ROOT/bin/swig}
```

we should also add something like:

```bash
[[ $SWIG_ROOT ]] || SWIG_ROOT=`brew --prefix swig` 
```

for the mac case, I guess.

**Comment by awegrzyn** [comment]
Improved recipe for swig has been merged: https://github.com/alisw/alidist/pull/999

**Pull request merged**
