### PR TITLE
GH Actions: Fix code formatter action

### PR DESCRIPTION
**Pull request by singiamtel**
Should fix the CI issues on #46 and #47

CC @ktf

**The required job `clang-format-8` has to be changed when merging**

### CODE REVIEW

**Comment by ktf** [comment]
Is this triggering new formatting errors?

**Comment by singiamtel** [comment]
> Is this triggering new formatting errors?

Hmm, good question. Apparently it wants to change ``//comments`` to ``// comments``, and remove a few newlines at the end of files. How should we proceed?

The changes when formatting everything:

```diff
 src/Configuration.cxx     | 3 +--
 src/Daemon.cxx            | 1 -
 src/Exception.cxx         | 1 -
 src/Iommu.cxx             | 1 -
 src/LineBuffer.cxx        | 3 +--
 src/MemPool.cxx           | 5 ++---
 src/Program.cxx           | 1 -
 src/SimpleLog.cxx         | 3 +--
 src/SuffixNumber.cxx      | 1 -
 src/System.cxx            | 1 -
 src/Thread.cxx            | 1 -
 test/TestBasicThread.cxx  | 1 -
 test/TestIommu.cxx        | 1 -
 test/TestSuffixNumber.cxx | 1 -
 test/TestSuffixOption.cxx | 1 -
 test/TestSystem.cxx       | 1 -
 test/testDaemon.cxx       | 1 -
 test/testFifo.cxx         | 1 -
 test/testSimpleLog.cxx    | 7 +++----
 test/testTimer.cxx        | 1 -
 20 files changed, 8 insertions(+), 28 deletions(-)
 ```

**Comment by ktf** [comment]
@sy-c can you have a look if this is fine for you? In principle it matches better the coding conventions and it seems trivial changes.

**Comment by sy-c** [comment]
Hello @ktf, ok for me.

**Pull request merged**
