### PR TITLE
[WIP] Improve finding Common from other packages

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@sy-c do not merge yet! This is what we've been discussing this morning. libInfoLogger needs to be adapted, and the recipes as well.

**Comment by sy-c** [comment]
very nice, thanks!

**Comment by awegrzyn** [comment]
@dberzano Can I progress with it?

**Comment by sy-c** [comment]
Closing, this was replaced by #17.

**Pull request closed without merging**
